source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

# Use local odysseus-core gem
gem 'odysseus-core', path: '../odysseus-core'

group :development, :test do
  gem 'pry-byebug', '~> 3.10'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.80'
end
