# lib/odysseus/secrets/encrypted_file.rb

require 'openssl'
require 'base64'
require 'yaml'
require 'securerandom'

module Odysseus
  module Secrets
    class EncryptedFile
      CIPHER = 'aes-256-gcm'
      KEY_ENV_VAR = 'ODYSSEUS_MASTER_KEY'

      class DecryptionError < Odysseus::Error; end
      class MissingKeyError < Odysseus::Error; end

      # @param path [String] path to encrypted secrets file
      def initialize(path)
        @path = path
      end

      # Check if the secrets file exists
      # @return [Boolean]
      def exists?
        File.exist?(@path)
      end

      # Read and decrypt secrets from file
      # @param key [String] master key (optional, defaults to ENV)
      # @return [Hash] decrypted secrets
      def read(key: nil)
        key ||= master_key
        raise MissingKeyError, "#{KEY_ENV_VAR} not set and no key provided" unless key

        encrypted_content = File.read(@path)
        decrypt(encrypted_content, key)
      end

      # Encrypt and write secrets to file
      # @param secrets [Hash] secrets to encrypt
      # @param key [String] master key (optional, defaults to ENV)
      def write(secrets, key: nil)
        key ||= master_key
        raise MissingKeyError, "#{KEY_ENV_VAR} not set and no key provided" unless key

        encrypted_content = encrypt(secrets, key)
        File.write(@path, encrypted_content)
      end

      # Generate a new random master key
      # @return [String] hex-encoded 32-byte key
      def self.generate_key
        SecureRandom.hex(32)
      end

      private

      def master_key
        ENV[KEY_ENV_VAR]
      end

      def encrypt(data, key)
        cipher = OpenSSL::Cipher.new(CIPHER)
        cipher.encrypt

        # Generate random IV
        iv = cipher.random_iv

        # Derive key from master key
        derived_key = derive_key(key, iv)
        cipher.key = derived_key

        # Encrypt
        yaml_data = data.to_yaml
        encrypted = cipher.update(yaml_data) + cipher.final
        auth_tag = cipher.auth_tag

        # Combine: iv + auth_tag + encrypted_data, all base64 encoded
        combined = Base64.strict_encode64(iv) + "\n" +
                   Base64.strict_encode64(auth_tag) + "\n" +
                   Base64.strict_encode64(encrypted)

        "# Odysseus encrypted secrets\n# Do not edit this file directly\n\n#{combined}"
      end

      def decrypt(content, key)
        # Remove comments and empty lines
        lines = content.lines.reject { |l| l.start_with?('#') || l.strip.empty? }

        raise DecryptionError, "Invalid encrypted file format" if lines.size < 3

        iv = Base64.strict_decode64(lines[0].strip)
        auth_tag = Base64.strict_decode64(lines[1].strip)
        encrypted = Base64.strict_decode64(lines[2].strip)

        cipher = OpenSSL::Cipher.new(CIPHER)
        cipher.decrypt
        cipher.iv = iv

        # Derive key from master key
        derived_key = derive_key(key, iv)
        cipher.key = derived_key
        cipher.auth_tag = auth_tag

        yaml_data = cipher.update(encrypted) + cipher.final
        YAML.safe_load(yaml_data, permitted_classes: [Symbol], symbolize_names: true) || {}
      rescue OpenSSL::Cipher::CipherError => e
        raise DecryptionError, "Failed to decrypt secrets: #{e.message}. Check your ODYSSEUS_MASTER_KEY."
      rescue ArgumentError => e
        raise DecryptionError, "Invalid encrypted file format: #{e.message}"
      end

      def derive_key(master_key, salt)
        # Use PBKDF2 to derive a proper key from the master key
        OpenSSL::PKCS5.pbkdf2_hmac(
          master_key,
          salt,
          10_000,      # iterations
          32,          # key length (256 bits)
          'sha256'
        )
      end
    end
  end
end
